apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-conductor-env
  namespace: {{ include "rollup.namespace" .  }}
data:
  ASTRIA_CONDUCTOR_LOG: "astria_conductor={{ .Values.config.logLevel }}"
  {{- if (index .Values "celestia-node").enabled }}
  TOKEN_SERVER_URL: "{{ include "celestiaNode.service.addresses.token" (index .Subcharts "celestia-node") }}"
  ASTRIA_CONDUCTOR_CELESTIA_NODE_HTTP_URL: "{{ include "celestiaNode.service.addresses.rpc" (index .Subcharts "celestia-node") }}"
  ASTRIA_CONDUCTOR_CELESTIA_NODE_WEBSOCKET_URL: "{{ include "celestiaNode.service.addresses.ws" (index .Subcharts "celestia-node") }}"
  {{- else }}
  TOKEN_SERVER_URL: "{{ .Values.config.celestia.token }}"
  ASTRIA_CONDUCTOR_CELESTIA_NODE_HTTP_URL: "{{ .Values.config.celestia.rpc }}"
  ASTRIA_CONDUCTOR_CELESTIA_NODE_WEBSOCKET_URL: "{{ .Values.config.celestia.ws }}"
  {{- end }}
  ASTRIA_CONDUCTOR_EXECUTION_RPC_URL: "http://127.0.0.1:{{ .Values.ports.executionGRPC }}"
  ASTRIA_CONDUCTOR_EXECUTION_COMMIT_LEVEL: "{{ .Values.config.rollup.executionCommitLevel }}"
  ASTRIA_CONDUCTOR_INITIAL_SEQUENCER_BLOCK_HEIGHT: "{{ .Values.config.sequencer.initialBlockHeight }}"
  ASTRIA_CONDUCTOR_SEQUENCER_GRPC_URL: "{{ .Values.config.sequencer.grpc }}"
  ASTRIA_CONDUCTOR_SEQUENCER_COMETBFT_URL: "{{ .Values.config.sequencer.rpc }}"
  ASTRIA_CONDUCTOR_SEQUENCER_BLOCK_TIME_MS: "{{ .Values.config.sequencer.blockTimeMs }}"
  ASTRIA_CONDUCTOR_NO_METRICS: "{{ not .Values.config.rollup.metrics.enabled }}"
  ASTRIA_CONDUCTOR_METRICS_HTTP_LISTENER_ADDR: "127.0.0.1:{{ .Values.ports.conductorMetrics }}"
  ASTRIA_CONDUCTOR_FORCE_STDOUT: "{{ .Values.global.useTTY }}"
  ASTRIA_CONDUCTOR_PRETTY_PRINT: "{{ .Values.global.useTTY }}"
  ASTRIA_CONDUCTOR_NO_OTEL: "{{ not .Values.config.rollup.otel.enabled }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.rollup.otel.endpoint }}"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "{{ .Values.config.rollup.otel.tracesEndpoint }}"
  OTEL_EXPORTER_OTLP_TRACES_TIMEOUT: "{{ .Values.config.rollup.otel.tracesTimeout }}"
  OTEL_EXPORTER_OTLP_TRACES_COMPRESSION: "{{ .Values.config.rollup.otel.tracesCompression }}"
  OTEL_EXPORTER_OTLP_HEADERS: "{{ .Values.config.rollup.otel.otlpHeaders }}"
  OTEL_EXPORTER_OTLP_TRACE_HEADERS: "{{ .Values.config.rollup.otel.traceHeaders }}"
  {{- if not .Values.global.dev }}
  {{- else }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-conductor-scripts
  namespace: {{ include "rollup.namespace" .  }}
data:
  start-conductor.sh: |
    {{- .Files.Get "files/scripts/start-conductor.sh" | nindent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-composer-env
  namespace: {{ include "rollup.namespace" .  }}
data:
  ASTRIA_COMPOSER_LOG: "astria_composer={{ .Values.config.logLevel }}"
  ASTRIA_COMPOSER_API_LISTEN_ADDR: "0.0.0.0:0"
  ASTRIA_COMPOSER_SEQUENCER_URL: "{{ .Values.config.sequencer.rpc }}"
  ASTRIA_COMPOSER_ROLLUPS: "{{ .Values.config.rollup.name }}::ws://127.0.0.1:{{ .Values.ports.wsRPC }}"
  ASTRIA_COMPOSER_MAX_BYTES_PER_BUNDLE: "{{ .Values.config.rollup.maxBytesPerBundle }}"
  ASTRIA_COMPOSER_MAX_SUBMIT_INTERVAL_MS: "{{ .Values.config.rollup.maxSubmitInterval }}"
  ASTRIA_COMPOSER_NO_METRICS: "{{ not .Values.config.rollup.metrics.enabled }}"
  ASTRIA_COMPOSER_METRICS_HTTP_LISTENER_ADDR: "127.0.0.1:{{ .Values.ports.composerMetrics }}"
  ASTRIA_COMPOSER_FORCE_STDOUT: "{{ .Values.global.useTTY }}"
  ASTRIA_COMPOSER_PRETTY_PRINT: "{{ .Values.global.useTTY }}"
  ASTRIA_COMPOSER_NO_OTEL: "{{ not .Values.config.rollup.otel.enabled }}"
  OTEL_EXPORTER_OTLP_ENDPOINT: "{{ .Values.config.rollup.otel.endpoint }}"
  OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "{{ .Values.config.rollup.otel.tracesEndpoint }}"
  OTEL_EXPORTER_OTLP_TRACES_TIMEOUT: "{{ .Values.config.rollup.otel.tracesTimeout }}"
  OTEL_EXPORTER_OTLP_TRACES_COMPRESSION: "{{ .Values.config.rollup.otel.tracesCompression }}"
  OTEL_EXPORTER_OTLP_HEADERS: "{{ .Values.config.rollup.otel.otlpHeaders }}"
  OTEL_EXPORTER_OTLP_TRACE_HEADERS: "{{ .Values.config.rollup.otel.traceHeaders }}"
  {{- if not .Values.secretProvider.enabled }}
  ASTRIA_COMPOSER_PRIVATE_KEY: "{{ .Values.config.sequencer.privateKey }}"
  {{- end }}
  {{- if not .Values.global.dev }}
  {{- else }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-faucet-env
  namespace: {{ include "rollup.namespace" .  }}
data:
  ETH_FAUCET_PROXYCOUNT: "{{ .Values.config.faucet.proxyCount }}"
  ETH_FAUCET_PORT: "{{ .Values.ports.faucet }}"
  ETH_FAUCET_EVM_PROVIDER_URL: "http://{{ .Values.config.rollup.name }}-evm-service:{{ .Values.ports.jsonRPC }}"
  ETH_FAUCET_AMOUNT: "{{ .Values.config.faucet.amount }}"
  {{- if not .Values.secretProvider.enabled }}
  ETH_FAUCET_EVM_PRIVATE_KEY: "{{ .Values.config.faucet.privateKey }}"
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-geth-env
  namespace: {{ include "rollup.namespace" .  }}
data:
  home_dir: "/home/geth"
  data_dir: "/home/geth/{{ .Values.config.rollup.name }}geth"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.config.rollup.name }}-executor-scripts
  namespace: {{ include "rollup.namespace" .  }}
data:
  geth-genesis.json: |
    {{- tpl (.Files.Get "files/genesis/geth-genesis.json") $ | nindent 4 }}
  init-geth.sh: |
    {{- tpl (.Files.Get "files/scripts/init-geth.sh") $ | nindent 4 }}
