kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.config.rollup.name }}-blockscout-svc
  namespace: {{ include "rollup.namespace" . }}
spec:
  selector:
    app: {{ .Values.config.rollup.name }}-astria-dev-cluster
  ports:
    - name: blockscout-svc
      port: {{ .Values.ports.blockscout }}
      targetPort: blockscout